<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DestinationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationsRepository extends EntityRepository
{
}
