<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Groupe_amisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Groupe_amisRepository extends EntityRepository
{
}
