UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        nom:
          type: string
          length: 50

        prenom:
          type: string
          length: 255


lifecycleCallbacks: { }