SiteBundle\Entity\Activite:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\ActiviteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
lifecycleCallbacks: {  }
