SiteBundle\Entity\Activites:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\ActivitesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        randonnee:
            type: string
            length: 255
        paintball:
            type: string
            length: 255
        cout:
            type: string
            length: 255
    lifecycleCallbacks: {  }
