SiteBundle\Entity\Destination:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\DestinationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pays:
            type: string
            length: 255
        transports:
            type: string
            length: 255
        cout:
            type: integer
    lifecycleCallbacks: {  }
