SiteBundle\Entity\Destination:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\DestinationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        allemagne:
            type: string
            length: 255
        paysBas:
            type: string
            length: 255
            column: pays_bas
        albanie:
            type: string
            length: 255
        espagne:
            type: string
            length: 255
        cout:
            type: integer
    lifecycleCallbacks: {  }
