SiteBundle\Entity\Destinations:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\DestinationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        France/Paris:

        cout:
            type: integer
    lifecycleCallbacks: {  }
