SiteBundle\Entity\Destination:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\DestinationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
