SiteBundle\Entity\Logements:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\LogementsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        camping:
            type: string
            length: 255
        hotel:
            type: string
            length: 255
        chambre_hote:
            type: string
            length: 255
        location_appartement:
            type: string
            length: 255
        location_mobile_home:
            type: string
            length: 255
        location_de_maison:
            type: string
            length: 255
        location_chalet:
            type: string
            length: 255
        cout:
            type: integer
    lifecycleCallbacks: {  }
