SiteBundle\Entity\Transports:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\TransportsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        location_vehicule:
            type: string
            length: 255
        avion:
            type: string
            length: 255
        bateau:
            type: string
            length: 255
        taxi:
            type: string
            length: 255
        transport_commun:
            type: string
            length: 255
    lifecycleCallbacks: {  }
