SiteBundle\Entity\Transport:
    type: entity
    table: null
    repositoryClass: SiteBundle\Repository\TransportRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
